from pathlib import Path

ROOT_FOLDER = Path(__file__).parent
FILES_FOLDER = ROOT_FOLDER / 'files'
ICON_PATH = FILES_FOLDER / 'calculator_icon.png'

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'
# PRIMARY_COLOR = '#ff0000'
# DARKER_PRIMARY_COLOR = '#d00000'
# DARKEST_PRIMARY_COLOR = '#9a1515'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUN_WIDTH = 400
